lft/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView

from project.models import Project, Userdata
from project.views import UserRegisterWizard
from project.forms import UserForm, UserdataForm, UserdataInterestsForm, UserdataSkillsForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lft.views.home', name='home'),
    # url(r'^lft/', include('lft.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	url(r'^$', 'project.views.home'),
	url(r'^user/login/$', 'project.views.user_login'),
	url(r'^user/logout/$', 'project.views.user_logout'),
	
	url(r'^project/create/$', 'project.views.project_create'),
	url(r'^project/list/$', 'project.views.project_list'),
	url(r'^project/(?P<project_id>\d+)/delete/$', 'project.views.project_delete'),
	
	url(r'^project/(?P<project_id>\d+)/position/create/$', 'project.views.project_createposition'),
	url(r'^project/(?P<project_id>\d+)/position/(?P<position_id>\d+)/delete/$', 'project.views.project_deleteposition'),
	url(r'^project/(?P<project_id>\d+)/position/(?P<position_id>\d+)/free/$', 'project.views.project_freeposition'),
	url(r'^project/(?P<project_id>\d+)/position/(?P<position_id>\d+)/accept/$', 'project.views.project_acceptposition'),
	url(r'^project/(?P<project_id>\d+)/position/(?P<position_id>\d+)/promote/$', 'project.views.project_promoteposition'),
	url(r'^project/(?P<project_id>\d+)/position/(?P<position_id>\d+)/demote/$', 'project.views.project_demoteposition'),
	
	url(r'^skill/reload/$', 'project.views.skill_reload'),
	url(r'^interest/reload/$', 'project.views.interest_reload'),
	
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	
	
	# /project/*
	#url(r'^project/$', 'project.views.index'),
	#url(r'^project/(?P<project_id>\d+)/$', 'project.views.detail'),
	
	
	# /user/*
	#url(r'^user/register$', 'project.views.userregister'),
	
	#url(r'^project/(?P<pk>\d+)/$',
    #    DetailView.as_view(
    #        model=Project,
    #        template_name='project/detail.html')),
	
	url(r'^project/(?P<project_id>\d+)/$', 'project.views.project_detail'),
	
	url(r'^user/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Userdata,
            template_name='userdata/detail.html')),
			
	#(r'^project/(?P<project_id>\d+)/position/create/$',
	#	UserRegisterWizard.as_view([PositionForm, PositionSkillForm], initial={'0':{'project': get_object_or_404(Project, pk=project_id)}, '1': {}})),
	(r'^user/register/$',
		UserRegisterWizard.as_view([UserForm, UserdataForm, UserdataInterestsForm, UserdataSkillsForm])),
)

"""
	url(r'^user/register/$',
		'project.views.user_register'),
	url(r'^user/register/2/$',
		'project.views.user_userdata'),
	url(r'^user/register/3/$',
		'project.views.user_interests'),
	url(r'^user/register/4/$',
		'project.views.user_skills'),
	"""

project/models.py
from django.db import models
from django.core import validators

from django.contrib.contenttypes import generic

from django.contrib.auth.models import User

from django.contrib.contenttypes.models import ContentType

from widgets import RankingWidget

import time

		
class Interest(models.Model):
	title = models.CharField(max_length=24)
	description = models.TextField(max_length=1024)
	
	creation_date = models.DateTimeField('created', auto_now_add=True)
	update_date = models.DateTimeField('last updated', auto_now=True)
	
	active = models.BooleanField(default=True)
	
	icon = models.ImageField(upload_to='icons', blank=True)
	
	parent = models.ForeignKey("self", blank=True, null=True)
	
	def __unicode__(self):
		return self.title
		
class Skill(models.Model):
	title = models.CharField(max_length=24)
	description = models.TextField(max_length=1024)
	
	creation_date = models.DateTimeField('created', auto_now_add=True)
	update_date = models.DateTimeField('last updated', auto_now=True)
	
	active = models.BooleanField(default=True)
	
	#levels = models.
	
	icon = models.ImageField(upload_to='icons', blank=True)
	
	parent = models.ForeignKey("self", blank=True, null=True)
	
	def __unicode__(self):
		return self.title
		
	value_range = (1, 5)
		
"""
class Ranking(models.Model):
	value_range = (1, 5)

	skill = models.ForeignKey(Skill)
	
	rank = models.IntegerField(validators=[validators.MinValueValidator(value_range[0]), validators.MaxValueValidator(value_range[1])])
	
	# only used for Position rankings, can be left false for User skills
	# if true, the requirement /must/ be met to be returned as a match
	strict = models.BooleanField(default=False)
	
	#position = models.ForeignKey(Position)
	content_type = models.ForeignKey(ContentType)
	object_id = models.PositiveIntegerField()
	
	target = generic.GenericForeignKey('content_type', 'object_id')
	
	def __unicode__(self):
		return '*' * self.rank
"""
		
class Userdata(models.Model):
	@staticmethod
	def avatar_filename(instance, filename):
		return "avatar/" + instance.user.username + "_" + time.gmtime() + "_" + filename
	
	#user = models.ForeignKey(User, unique=True)
	user = models.OneToOneField(User)
	
	avatar = models.ImageField(upload_to=avatar_filename, blank=True)
	
	bio = models.TextField(max_length=1024, blank=True)
	
	url = models.URLField(max_length=200, blank=True)
	
	#interests = generic.GenericRelation(Tag)
	#rankings = generic.GenericRelation(Ranking)
	
	interests = models.ManyToManyField(Interest, through='UserInterest')
	skills = models.ManyToManyField(Skill, through='UserSkill')
	
	# location
	
	def __unicode__(self):
		return self.user.username
	
	
		
class Project(models.Model):
	title = models.CharField(max_length=64, unique=True)
	description = models.TextField(max_length=1024)
	
	creation_date = models.DateTimeField('created', auto_now_add=True)
	update_date = models.DateTimeField('last updated', auto_now=True)
	
	open = models.BooleanField(default=True)
	
	url = models.URLField(max_length=200, blank=True)
	
	#tags = models.ManyToManyField(Tag, blank=True)
	#tags = generic.GenericRelation(Tag, blank=True)
	
	interests = models.ManyToManyField(Interest, through='ProjectInterest')
	
	members = models.ManyToManyField(Userdata, through='ProjectRelation')
	
	def __unicode__(self):
		return self.title
		
class ProjectRelation(models.Model):
	user = models.ForeignKey(Userdata)
	project = models.ForeignKey(Project)
	
	admin = models.BooleanField(default=False)
	
	#position = models.OneToOneField('Position')
	
	creation_date = models.DateTimeField('created', auto_now_add=True)
	update_date = models.DateTimeField('last updated', auto_now=True)
	
	def __unicode__(self):
		return self.user.user.username + ' of ' + self.project.title
	
class Position(models.Model):
	title = models.CharField(max_length=64)
	description = models.TextField(max_length=1024)
	
	creation_date = models.DateTimeField('created', auto_now_add=True)
	update_date = models.DateTimeField('last updated', auto_now=True)
	
	project = models.ForeignKey(Project)
	
	project_relation = models.OneToOneField(ProjectRelation, null=True, on_delete=models.SET_NULL)
	
	# A restricted position requires a project admin to accept a user application
	# Any user can accept an open position
	restricted = models.BooleanField(default=True)
	
	# A repeating position can accept any number of users
	# For example, a volunteer open source project may be looking for any number of people to
	# work on bug fixes, etc.
	# Otherwise, the position will be removed from searches once it has been filled
	repeating = models.BooleanField(default=False)
	
	#rankings = generic.GenericRelation(Ranking)
	
	skills = models.ManyToManyField(Skill, through='PositionSkill')
	
	def __unicode__(self):
		return self.title
		
admin_position_default = Position(
	id=None,
	title='Project Leader',
	description='Benevolent dictator for life',
)

class UserInterest(models.Model):
	user = models.ForeignKey(Userdata)
	interest = models.ForeignKey(Interest)
	
	def __unicode__(self):
		return self.interest.title

class UserSkill(models.Model):
	user = models.ForeignKey(Userdata)
	skill = models.ForeignKey(Skill)
	
	rank = models.IntegerField(validators=[validators.MinValueValidator(Skill.value_range[0]), validators.MaxValueValidator(Skill.value_range[1])])
	
	def __unicode__(self):
		return self.skill.title + ': ' + ('*' * self.rank)
	
class ProjectInterest(models.Model):
	project = models.ForeignKey(Project)
	interest = models.ForeignKey(Interest)
	
	def __unicode__(self):
		return self.interest.title
	
class PositionSkill(models.Model):
	position = models.ForeignKey(Position)
	skill = models.ForeignKey(Skill)
	
	# if true, the requirement /must/ be met to be returned as a match
	strict = models.BooleanField(default=False)
	
	rank = models.IntegerField(validators=[validators.MinValueValidator(Skill.value_range[0]), validators.MaxValueValidator(Skill.value_range[1])])
	
	def __unicode__(self):
		return self.skill.title + ': ' + ('*' * self.rank)
		
class Invite(models.Model):
	position = models.ForeignKey(Position)
	
	message = models.TextField(max_length=1024)
	
	#sender = models.ForeignKey(User)
	#recipient = models.ForeignKey(User)

	read = models.BooleanField(default=False)
	
class Application(models.Model):
	position = models.ForeignKey(Position)
	
	message = models.TextField(max_length=1024)

	#sender = models.ForeignKey(User)
	
	read = models.BooleanField(default=False)
	
	accepted = models.NullBooleanField(default=None)
	
	

project/forms.py
from django.db import models
from django.core import validators
from django import forms

from widgets import RankingWidget

from django.forms import ModelForm, Form

from project.models import Userdata, Project, Position, Interest, Skill, UserInterest, UserSkill
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.forms.models import fields_for_model, ModelMultipleChoiceField
from django.forms import ValidationError


class UserForm(Form):
	username = fields_for_model(User, ['username'])['username']
	password = fields_for_model(User, ['password'])['password']
	password_confirm = fields_for_model(User, ['password'])['password']
	password_confirm.label = "Confirm password"
	
	email = fields_for_model(User, ['email'])['email']
	email.required = True
	email_confirm = fields_for_model(User, ['email'])['email']
	email_confirm.label = "Confirm E-mail"
	email_confirm.required = True
	
	first_name = fields_for_model(User, ['first_name'])['first_name']
	last_name = fields_for_model(User, ['last_name'])['last_name']
	
	def clean(self):
		cleaned_data = super(UserForm, self).clean()
		
		user_password = cleaned_data.get("password")
		user_password_confirm = cleaned_data.get("password_confirm")
		
		if user_password != user_password_confirm:
			raise ValidationError("Entered passwords do not match")
			
		user_email = cleaned_data.get("email")
		user_email_confirm = cleaned_data.get("email_confirm")
		
		if user_email != user_email_confirm:
			raise ValidationError("Entered emails do not match")
		
		return cleaned_data
	
class UserdataForm(Form):
	avatar = fields_for_model(Userdata, ['avatar'])['avatar']
	bio = fields_for_model(Userdata, ['bio'])['bio']
	url = fields_for_model(Userdata, ['url'])['url']
	
class UserdataInterestsForm(Form):
	#interests = fields_for_model(Userdata, ['interests'])['interests']
	interests = ModelMultipleChoiceField(queryset=Interest.objects.filter(active=True))

class UserdataSkillsForm(Form):
	#test = forms.IntegerField(required=False)

	def __init__(self, *args, **kwargs):
		#extra_fields = kwargs.pop('extra', 0)
		super(UserdataSkillsForm, self).__init__(*args, **kwargs)
		
		self.fields['workaround'] = forms.IntegerField(required=False)
		
		for skill in Skill.objects.filter(active=True):
			#if skill.active:
			self.fields[str(skill.id)] = forms.IntegerField(
				label=skill.title, 
				validators=[validators.MinValueValidator(Skill.value_range[0]), validators.MaxValueValidator(Skill.value_range[1])],
				widget=RankingWidget,
				required=False)
					
	
"""
class ProjectForm(ModelForm):
	class Meta:
		model = Project
		fields = (
			'title',
			'description',
			'open',
			'url',
			'interests',
		)
	
	def clean(self):
		cleaned_data = super(ContactForm, self).clean()
		
"""

class ProjectForm(Form):
	title = fields_for_model(Project, ['title'])['title']
	description = fields_for_model(Project, ['description'])['description']
	open = fields_for_model(Project, ['open'])['open']
	url = fields_for_model(Project, ['url'])['url']
	
	interests = ModelMultipleChoiceField(queryset=Interest.objects.filter(active=True), required=False)

"""	
class PositionForm(Form):
	#project = forms.ModelChoiceField(Project, editable=False)

	title = fields_for_model(Position, ['title'])['title']
	description = fields_for_model(Position, ['description'])['description']
"""
	
#"""
class PositionForm(ModelForm):
	class Meta:
		model = Position
		fields = (
			'title',
			'description',
			
		)
#"""
	
#class Userdata
	
#class RankingForm(Form):
#	skill = fields_for_model(Ranking, ['skill'])
#	rank = fields_for_model(Ranking, ['rank'])
	
class LoginForm(Form):
	username = fields_for_model(User, ['username'])['username']
	password = fields_for_model(User, ['password'])['password']
	
	def clean(self):
		cleaned_data = super(LoginForm, self).clean()
		
		self.user_cache = authenticate(username=cleaned_data.get("username"), password=cleaned_data.get("password"))
		
		if self.user_cache is None:
			raise ValidationError("User and password combination not found")
		
		return cleaned_data
		
	

templates/project/create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form method="post" action=""> {% csrf_token %}
	<table>
		{{form}}
	</table>
	<input type="submit" value="Create" />
</form>
{% endblock %}

templates/project/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<h1>{{ project.title }}</h1>
	<p>{{ project.description }}</p>
	{% if project.project_url %}
		<p>{{project.project_url}}</p>
	{% endif %}
	Created: {{project.creation_date}}<br />
	Modified: {{project.update_date}}<br />
	</p>
	<p>
	{% if project.open %}
		Open
	{% else %}
		Closed
	{% endif %}
	<br />
	</p>
	
	{% if can_edit %}
		<a href="/project/{{ project.id }}/delete" onClick="return confirm('This action is permanent and cannot be undone')">Delete project</a> <br />
	{% endif %}

	{% if project.tags %}
		Tags
		<ul>
			{% for tag in project.tags.all %}
				<li>
					{{tag.title}}
				</li>
			{% endfor %}
		</ul>
	{% endif %}


	{% if project.position_set %}
		Positions <br />
		
		{% if can_edit %}
			<a href="/project/{{ project.id }}/position/create">Add New Position</a><br />
		{% endif %}
		
		<ul>
			{% for position in project.position_set.all %}
				<li>
					{{ position.title }}
					{% if can_edit %}
						{# Don't allow deleting own position #}
						{% if position.project_relation.user.id != user.userdata.id %}
							<a href="/project/{{ project.id }}/position/{{ position.id }}/delete" onClick="return confirm('This action is permanent and cannot be undone')">delete</a>
						{% endif %}
					{% endif %}
					<br />
					{% if position.project_relation %}
						Held by: {{ position.project_relation.user.user.username }} 
						{% if position.project_relation.admin %}
							[Admin]
						{% endif %}
						{% if can_edit %}
							{% if position.project_relation.user.id != user.userdata.id %}
								{# Don't allow a user to de-admin themselves or remove their own position (for now) #}
								
								<a href="/project/{{ project.id }}/position/{{ position.id }}/free" onClick="return confirm('This action is permanent and cannot be undone')">Remove</a> 
								
								{% if position.project_relation.admin %}
									<a href="/project/{{ project.id }}/position/{{ position.id }}/demote" onClick="return confirm('This action is permanent and cannot be undone')">demote</a>
								{% else %}
									<a href="/project/{{ project.id }}/position/{{ position.id }}/promote" onClick="return confirm('This action is permanent and cannot be undone')">promote</a>
								{% endif %}
							{% endif %}
						{% endif %}
					{% else %}
						{% if not is_member %}
							<a href="/project/{{ project.id }}/position/{{ position.id }}/accept" onClick="return confirm('This action is permanent and cannot be undone')">Accept position</a>
						{% endif %}
					{% endif %}
				</li>
			{% endfor %}
		</ul>
	{% endif %}
{% endblock %}

templates/project/list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	{% if project_list %}
		<ul>
		{% for project in project_list %}
			<li><a href="/project/{{ project.id }}/">{{ project.title }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No projects are available.</p>
	{% endif %}
{% endblock %}

templates/project/newposition.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form method="post" action=""> {% csrf_token %}
	<table>
		{{form}}
	</table>
	<input type="submit" value="Create" />
</form>
{% endblock %}